config/routes.rb
Rails.application.routes.draw do

  get 'genres/index'
  get 'genres', to: 'genres#index'
  get 'genres/add'
  post 'genres/add'
  get 'genres/:id', to: 'genres#show'

  get 'genres/:id/edit', to: 'genres#edit'
  patch 'genres/:id/edit', to: 'genres#edit'
  get 'genres/:id/delete', to: 'genres#delete'
  post 'genres/:id/delete', to: 'genres#delete'

  get 'posts/like_ranking'

  devise_for :users

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts

  validates :name, presence: {message: 'は必須項目です。'}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, {presence: true}
  validates :post_id, {presence: true}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user
  belongs_to :genre

  validates :title, :summary, :content, :genre_id, presence: {message:'は、必須項目です。'}

  scope :recent, -> (count = 15){ order('created_at desc').limit(count) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts, dependent: :destroy
         has_many :likes, dependent: :destroy

         validates :nickname, presence: {message:'は、必須項目です。'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find params[:id]
    @posts = Post.where(id: params[:genre_id]).order(created_at: :desc)
    #@post = Post.where('genre_id = ?', params[:id]).order('created_at desc')
    #redirect_to '/genres/:id'
  end

  def add
    @genre = Genre.new
    if request.post? then
      @genre = Genre.create(genre_params)
      #@genre.save
      redirect_to '/genres', data: {"turbolinks" => false}
    end
  end

  def edit
    @genre = Genre.find params[:id]
    if request.patch? then
      @genre.update genre_params
      redirect_to '/genres', data: {"turbolinks" => false}
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name, :memo, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    likes_count
    render :index
    #redirect_to("/posts/#{params[:post_id]}")
  end

  def destroy
    set_like
    @like.destroy
    @like = nil
    likes_count
    render :index
    #redirect_to("/posts/#{params[:post_id]}")
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_like
    @like = current_user.likes.find_by(post_id: params[:post_id])
  end

  def likes_count
    @likes_count = Like.where(post_id: @post.id).count
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(15).recent
    @like_ranking = Post.where(id: Like.group(:post_id).order('count(post_id) desc').limit(15).pluck(:post_id))
    @genres = Genre.all
  end

  def like_ranking
    @posts = Post.find(Like.group(:post_id).order('count(post_id) desc').limit(50).pluck(:post_id))
  end

  def genre
    @genre = Genre.find params[:id]
    @post = Post.where('genre_id = ?', params[:id]).order('created_at desc')
    #redirect_to '/genres/:id'
  end


  def show
    @user = User.find_by(id: @post.user_id)
    @like = current_user.likes.find_by(post_id: @post.id) if user_signed_in?
    @likes_count = Like.where(post_id: @post.id).count
    @genres = Genre.all
    @posts = Post.where(id: params[:genre_id]).order(created_at: :desc)
    @genres = @posts.genre
  end

  # GET /posts/new
  def new
    @post = Post.new
    @genres = Genre.all
  end

  # GET /posts/1/edit
  def edit
    @genres = Genre.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @genres = Genre.all
    if @post.save
      #make_picture
      redirect_to @post, notice: '投稿しました。投稿ありがとうございます。'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @genres = Genre.all
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :summary, :content, :user_id, :genre_id)
    end

    def correct_user
      if current_user.id != @post.user_id
         redirect_to posts_path, notice: '他のユーザーの投稿は編集できません。'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  #def index
    #@users = User.all
  #end

  # GET /users/1
  # GET /users/1.json
  def show
    if params[:format].present?
      @user = User.find(params[:format])
    else
      @user = User.find(params[:id])
    end

    @posts = @user.posts
    @likes = Like.where(user_id: @user.id)
  end

  # GET /users/new
  def new
    #@user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    #@user = User.new(user_params)

    #respond_to do |format|
      #if @user.save
      #  format.html { redirect_to @user, notice: 'User was successfully created.' }
      #  format.json { render :show, status: :created, location: @user }
      #else
        #format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #respond_to do |format|
    #    format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @user }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @user.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    #@user.destroy
    #respond_to do |format|
    #  format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    #  format.json { head :no_content }
    #end
  end

  #private
    # Use callbacks to share common setup or constraints between actions.
    #def set_user
    #  @user = User.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    #def user_params
    #  params.require(:user).permit(:nickname, :profile, :post_id, :like_id)
    #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/genres/add.html.erb
<h1>Genres#add</h1>

<p>ジャンル・データの作成</p>
<% if @genre.errors.any? %>
<ui>
  <% @genre.errors.full_messages.each do |err| %>
    <li><%= err %></li>
  <% end %>
</ui>
<% end %>

<table>
<%= form_for(@genre, url:{controller: 'genres', action: 'add'}) do |form|%>
<tr>
  <th>name</th>
  <td><%= form.text_field :name %></td>
</tr>
<tr>
  <th>memo</th>
  <td><%= form.text_field :memo %></td>
</tr>
<tr>
  <th></th>
  <td><%= form.submit "送信" %></td>
</tr>
<% end %>
</table>

app/views/genres/destroy.html.erb
<h1>Genres#destroy</h1>
<p>Find me in app/views/genres/destroy.html.erb</p>

app/views/genres/edit.html.erb
<h1>Genres#edit</h1>

<p>「<%= @genre.name %>」ジャンルの編集</p>

<% if @genre.errors.any? %>
<ui>
  <% @genre.errors.full_messages.each do |err| %>
    <li><%= err %></li>
  <% end %>
</ui>
<% end %>

<table>
<%= form_for(@genre, url:{controller: 'genres', action: 'edit'}) do |form|%>
<tr>
  <th>name</th>
  <td><%= form.text_field :name %></td>
</tr>
<tr>
  <th>memo</th>
  <td><%= form.text_field :memo %></td>
</tr>
<tr>
  <th></th>
  <td><%=form.submit "送信" %></td>
</tr>
<% end %>
</table>

app/views/genres/index.html.erb
<h1>Genres#index</h1>

<p>ジャンル・データの一覧</p>
<table>
<tr>
  <th>Id</th><th>name</th><th>memo</th>
</tr>

<% if @genres.present? %>
    <% @genres.each do |genre| %>
    <tr>
      <%#= link_to @post.user.nickname, user_path(@user.id) %>
      <td><%= genre.id %></td>
      <td><%#= link_to genre.name, genres_path(genre.id) %></td>
      <td><%#= link_to(genre.name, "/genres/#{genre.id}", {:action=>"index", :controller=>"posts"}, id: genre.id) %></td>
      <td><%= link_to(genre.name, "/genres/#{genre.id}", controller: "posts", action: "show", id: genre.id) %></td>
      <td><%#= link_to genre.name, "/genres/#{genre.id}", posts_path(genre_id) %></td>
      <td><%= genre.memo %></td>
      <td><%= link_to("Edit", "/genres/#{genre.id}/edit") %></td>
    </tr>
    <% end %>
<% end %>

</table>
<p><%= link_to("ジャンル新規作成", "/genres/add" ) %></p>

app/views/genres/show.html.erb
<!-- ジャンル別投稿一覧-->
<h1>「<%= @genre.name %>」の投稿</h1>



<%# unless @posts.present? %>
  <p><%= @genre.name %>の投稿はまだありません。</p>
<%# end %>

<%# if @posts.present? %>
<%# unless @post.genre_id = @genre.id %>
   <p><%#= @genre.name %>の投稿はまだありません。</p>
<%# end %>
    <% @posts.each do |post| %>
       <%= post.title %>
       <%= post.summary %>
    <% end %>
<%# end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>IdeaNetwork</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

　　<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
   </head>

    <body>
      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand mr-auto mr-lg-0" href="#">Offcanvas navbar</a>
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">IdeaNetworkとは <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <%= link_to "投稿を見る", posts_path, class:"nav-link" %>
              </li>
              <% if user_signed_in? %>　
                  <li class="nav-item">
                    <%= link_to "投稿する", new_post_path, class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "マイページ", user_path(current_user.id), class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete , class:"nav-link" %>
                  </li>
              <% else %>
                  <li class="nav-item">
                    <%= link_to "無料会員登録", new_user_registration_path , class:"nav-link" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path , class:"nav-link" %>
                  </li>
              <% end %>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <a class="dropdown-item" href="#">Action</a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    </body>
</html>

app/views/likes/_index.html.erb
<% if user_signed_in? %>
  <% unless @post.user_id == current_user.id %>
    <% if @like.present? %>
      <div class="like-now floats">
        <%= link_to post_like_path(post_id: @post.id, id: @like.id), method: :delete, remote: true do %>
          <%#<i class="fa fa-heart fa-2x like-now"></i>%>
          <span class="fa fa-heart like-btn-unlike"></span>
        <% end %>
      </div>
    <% else %>
      <div class="like-not floats">
        <%= link_to post_likes_path(post_id: @post.id), method: :post, remote: true do %>
          <%#<i class="fa fa-heart fa-2x like-not"></i>%>
          <span class="fa fa-heart like-btn"></span>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>
<div class="like-count floats">いいね！<%= @likes_count %>件</div>

app/views/likes/index.js.erb
$("#like_area").html("<%= j(render partial: 'index') %>")

app/views/posts/_article.html.erb
<table class="table-responsive table table-striped table-bordered">>
  <%#<table class="table table-condensed">%>

  <thead>
    <tr>
      <th>Title</th>
      <th>いいね</th>
      <th>Summary</th>
      <th>Content</th>
      <th>User</th>
      <th>Genre</th>
      <th colspan="6"></th>

      <%#<th width="10%">Title</th>%>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><span class="fa fa-heart like-btn"><%= post.likes.count %></span>件</td>
        <td><%= post.summary %></td>
        <td><%= post.content %><%= link_to 'もっと見る', post %></td>
        <td><%= post.user.nickname %></td>
        <td><%= post.genre.try(:name) %></td>
        <!--
          <% if post.genre.present? %>
            <td><%= post.genre.name %></td>
          <% end %>
        -->
        <td><%#= link_to(post.genre.try(:name), "/@genres/#{@genre.id}", controller: "posts", action: "show", id: @genre.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :summary %>
    <%= form.text_area :summary, id: :post_summary %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :post_content %>
  </div>

  <div class="field">
    <%= form.label :genre_id %>
    <%= form.collection_select(:genre_id, Genre.all, :id, :name) %>
    <%#= form.label :genre.try(:name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="body-full">
    <br>
  <!-- 検索機能 -->
  <div class="container-fluid">
    <div class="card search-box">

      <div class="card-body">
        <span class="box-title"><i class="fa fa-search fa-fw"></i>検索</span>
        <%#= search_form_for(@q, method: :get) do |f| %>
        <%#= search_form_for @q ,url: {controller: "posts", action: "index"} do |f| %>
        <%= search_form_for @q do |f| %>
        <div class="row">
          <div class="col-6 col-md-3">
            <div class="form-group">
              <%#= f.label :genre_id_eq, '分野' %>
              <%= f.label :genre_id, '分野　' %>
              <%#= f.select :genre_id_eq, [["観光","観光"],["生活","生活"],["不便","不便"],["言語","言語"],["",""],["",""],["",""],["",""]], {include_blank: true}, {class: 'form-control'} %>
              <%= f.select :genre_id_eq, Genre.all.map{|genre| [genre.name, genre.id]} %>
            </div>
          </div>
          <div class="search-button">
            <%= f.submit 'この条件で検索する', class: "btn btn-sm standard-button" %>　<%= link_to '検索条件クリア', url_for, class: "btn btn-light btn-sm" %>
          </div>
         </div>
        <% end %>
       </div>
      </div>
  </div>
     <!-- 検索機能ここまで -->

  <!-- 一覧表示 -->
  <h1>Idea 一覧 </h1>
  <!-- ページング機能 -->
  <div><%= page_entries_info @posts %></div>

  <div class="container-fluid index-body">
    <div class="row">
    <div id="main" class="col-sm-12 col-md-8">


      <% unless @posts.present? %>
        <p>投稿はまだありません。</p>
      <% end %>
      <%= render partial: "article", locals: {posts: @posts} %>
  　　
  <!-- 一覧表示ここまで -->
 <br>
  <!-- ページング機能 -->
      <div><%= paginate @posts %></div>
      <%#</main>%>
      <br>

      <%= link_to '投稿する', new_post_path %>
      </div>


<%#<p>%>
<!-- サイドバー -->
<div id="side" class="col-sm-12 col-md-4">
    <!-- いいねが多い投稿一覧機能 -->
      <div class="rank-box height="10px"">
        <span class="rank-box-title"><span class="fa fa-heart like-btn"></span>いいね！ランキング</span>
        <div class="not-under">
          <% @like_ranking.each.with_index(1) do |post, i| %>
            <%= link_to post do %>
              <div class ="rank">
                <table class="table table-sm height="300px""  >
                  <tbody>
                    <tr>
                      <td class="border-top-0"><%= i %>位　「<%= post.title %>」</td>
                    </tr>
                    <tr>
                      <td class="border-top-0"> -<%= post.genre.try(:name) %>-    <span class="fa fa-heart like-btn"><%= post.likes.count %></span>件</td>
                    </tr>
                    <tr>
                      <td class="border-top-0"> (要約：<%= post.summary %>) </td>
                    </tr>
                    <tr>
                      <td class="border-top-0"> (内容：<%= post.content %>　<%= link_to 'もっと見る', post %>)- </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            <% end %>
          <% end %>
        </div>
        <%= link_to 'もっと見る', posts_like_ranking_path, style: "text-decoration: underline" %>
     </div>
       <!-- いいねが多い投稿一覧機能ここまで -->
  </div>


    </div>
   </div>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @post.summary %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<!-- いいね追加・削除 -->
      <div id="like_area">
        <%= render partial: 'likes/index' %>
      </div>

<p>
  <strong>Genre:</strong>
  <%#= @post.genre_id %>
  <%= @post.genre.try(:name) %>
</p>

<p>
  <strong>Nickname:</strong>
  <%#= link_to @post.user.nickname, controller::users, action::show %>
  <%#= link_to @post.user.nickname, user_path(current_user.id) %>
  <%= link_to @post.user.nickname, user_path(@user.id) %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Back', posts_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Nickname</th>
      <th>Profile</th>
      <th>Post</th>
      <th>Like</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nickname %></td>
        <td><%= user.profile %></td>
        <td><%= user.post_id %></td>
        <td><%= user.like_id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @user.nickname %>さんのページ</h2>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 col-md-8">
          <table class="table table-striped table-bordered">
          <tr>
            <td colspan="2">Nickname: </td>
          </tr>
          <tr>
            <td colspan="2">
              <%= @user.nickname %>
            </td>
          </tr>
          <tr>
            <td colspan="2">Profile: </td>
          </tr>
          <tr>
            <td colspan="2">
              <%= @user.profile %>
            </td>
          </tr>
          </table>
      </div>
    </div>
  </div>

  <%= link_to "プロフィールを編集する", edit_user_registration_path, method: :get %>
  <%#= link_to "プロフィールを編集する", edit_user_detail_path(current_user.user_detail.id),method: :get %>
  <%#= link_to "プロフィールを設定する", new_user_detail_path,method: :get %>


  <!-- 本人の投稿一覧 -->
    <div>
      <h5><%= @user.nickname %>さんの投稿一覧</h5>
      <% unless @posts.present? %>
        <p><%= @user.nickname %>さんの投稿はまだありません。</p>
        <% if current_user.present? %>
          <% if @user.id == current_user.id %>
            <p>投稿してみましょう！➡︎ <%= link_to "投稿はこちらから", new_post_path, class: "standard-button" %></p>
          <% end %>
        <% end %>
      <% end %>

      <%#<%= render partial: "posts/article", locals: {posts: @posts}  %>
      <div class="not-under">

        <%= render partial: "posts/article", locals: {posts: @posts}  %>

      </div>

      <%#<% if current_user.present? %>
        <%#<% if @user.id == current_user.id && @posts.present? %>
          <%#<p>投稿ありがとうございます！これまでに経験された他のキャリアについても投稿してみませんか？➡︎ <%= link_to "投稿はこちらから", new_post_path, class: "standard-button" %></p>
        <%#<% end %>
      <%#<% end %>
    </div>
    <br>

    <!-- 本人がいいね！を押した投稿一覧 -->
  <div>
    <h5><%= @user.nickname %>さんが<span class="fa fa-heart like-btn"></span>いいね！をした投稿一覧</h5>
    <% unless @likes.present? %>
      <p><%= @user.nickname %>さんが<span class="fa fa-heart like-btn"></span>いいね！をした投稿はまだありません。</p>
    <% end %>

    <%#<%= render partial: "posts/article", locals: {posts: @want_posts}  %>
    <div class="not-under">
      <div class="col-sm-12 col-md-8">
      <table class="table-responsive table table-striped table-bordered">
        <thead>
          <tr>
            <th width="10%">Title</th>
            <th width="5%">いいね</th>
            <th width="20%">Summary</th>
            <th width="20%">Content</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
           <% @likes.each do |like| %>
           <% post = Post.find_by(id: like.post_id) %>
            <tr>
              <td><%= post.title %></td>
              <td><span class="fa fa-heart like-btn"><%= post.likes.count %></span>件</td>
              <td><%= post.summary %></td>
              <td><%= post.content %><%= link_to 'もっと見る', post %></td>
              <td><%#= like_post.content %><%#= link_to 'もっと見る', "@posts/#{post.id}", controllers: "@posts", action: "show" %></td>
            </tr>
           <% end %>
        </tbody>
      </table>
    </div>
   </div>
  </div>

  <%= link_to '投稿一覧へ', posts_path %>

</div>